constructor_site/constructor_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',auth_views.LoginView.as_view(),name='login'),
    path('', include('management_site.urls', namespace='management_site')),
    path('figma/', include('figma.urls')),
    path('<str:user_site>/sale/clothes/', include('sale_clothes.urls')),
    path('crm/', include('mini_crm.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, 
		                 document_root=settings.MEDIA_ROOT)

constructor_site/figma/urls.py
from django.urls import path
from . import views

app_name = 'figma'
urlpatterns = [
    path('',views.ClientIndexView.as_view(), name ='index'),

    
] 

constructor_site/sale_clothes/urls.py
from django.urls import path
from . import views

app_name = 'clothes'
urlpatterns = [
    path('',views.ClientIndexView.as_view(), name ='index'),
    path('good/list/<int:category>/',views.GoodListView.as_view(), name ='good_list'),
    path('good/list/<int:category>/<int:subcategory>',views.GoodListView.as_view(), name ='good_list'),
    path('detail/<int:good>',views.DetailView.as_view(), name ='detail'),
    path('add/bag/<int:good>',views.AddBagView.as_view(), name ='add_bag'),
    path('creat/index',views.ConstructIndexView.as_view(), name ='creat_index'),
    path('creat/good/list/<int:category>',views.CreatGoodListView.as_view(), name ='creat_good_list'),
    path('creat/category',views.CategoryCreateView.as_view(), name ='creat_category'),
    path('creat/good',views.GoodCreateView.as_view(), name ='creat_good'),
    path('creat/subcategory/<int:category>',views.SubcategoryCreateView.as_view(), name ='creat_subcategory'),
    path('update/title/good',views.UpdateTitleGoodView.as_view(), name ='update_title'),
    path('update/additional/data',views.UpdateOrCreateAdditionalDataView.as_view(), name ='update_additional_data'),
    path('update/category',views.UpdateCategoryView.as_view(), name ='update_category'),
    path('delete/category',views.DeleteCategoryView.as_view(), name ='delete_category'),
    path('delete/good',views.DeleteGoodView.as_view(), name ='delete_good'),

] 

constructor_site/templates/clothes/constructor-site/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load sale_tags %}
    <head>
        <meta charset="utf-8">
        <title>Men's Shop</title>
        <meta name="viewport" content="width=device-width, initial-scale=0.9">
        <link href="{% static 'clothes/css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
        <link rel="stylesheet" href="{% static 'css/figma/bootstrap.min.css' %}"/>
        <link href="{% static 'clothes/css/themify-icons.css' %}" rel="stylesheet" type="text/css" media="all" />
        <link href="{% static 'clothes/css/flexslider.css' %}" rel="stylesheet" type="text/css" media="all" />
        <link href="{% static 'clothes/css/lightbox.min.css' %}" rel="stylesheet" type="text/css" media="all" />
        <link href="{% static 'clothes/css/ytplayer.css' %}" rel="stylesheet" type="text/css" media="all" />
        <link href="{% static 'clothes/css/theme.css' %}" rel="stylesheet" type="text/css" media="all" />
        <link href="{% static 'clothes/css/custom.css' %}" rel="stylesheet" type="text/css" media="all" />
        <link href='http://fonts.googleapis.com/css?family=Lato:300,400%7CRaleway:100,400,300,500,600,700%7COpen+Sans:400,500,600' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

    </head>
    <body>
        <div class="nav-container">
            <a id="top"></a>
            <nav>
                <div class="nav-bar">
                    <div class="module widget-handle mobile-toggle right visible-sm visible-xs">
                        <i class="ti-menu"></i>
                    </div>
                    <div class="module-group right">
                        <div class="module left">
                            <ul class="menu">
                                <li class="has-dropdown" >
                                        <!-- Button trigger modal -->
                                    <a href="{% url 'clothes:creat_category' user_site=user_site %}">
                                      добавить категории
                                    </a>
                                </li>
                              {% for category in categories %}
                                <li class="has-dropdown">
                                    <a href="{% url 'clothes:creat_good_list' category=category.id user_site=user_site %}" data-id="{{category.id}}" class="update-data update-category" contenteditable="false">
                                        {{category.title}}
                                    </a>
                                    <span class="pen-update" data-id="{{category.id}}"><i class="fas fa-pencil-alt"></i></span>
                                    <span class="delete-category" data-id="{{category.id}}"><i class="fas fa-times"></i></span>
                                </li>
                              {% endfor %}
                            </ul>
                        </div>
                        <!--end of menu module-->
                        <div class="module widget-handle search-widget-handle left">
                            <div class="search">
                                <i class="ti-search"></i>
                                <span class="title">Search Site</span>
                            </div>
                            <div class="function">
                                <form class="search-form">
                                    <input type="text" placeholder="Type Here" />
                                </form>
                            </div>
                        </div>
                        <div class="module widget-handle cart-widget-handle left">
                            <div class="cart">
                                <i class="ti-bag"></i>
                                <span class="label number">2</span>
                                <span class="title">Shopping Cart</span>
                            </div>
                            <div class="function">
                                <div class="widget">
                                    <h6 class="title">Shopping Cart</h6>
                                    <hr>
                                    <ul class="cart-overview">
                                        <li>
                                            <a href="#">
                                                <img alt="Product" src="img/shop-widget-1.png" />
                                                <div class="description">
                                                    <span class="product-title">Canvas Backpack</span>
                                                    <span class="price number">$39.90</span>
                                                </div>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <img alt="Product" src="img/shop-widget-2.png" />
                                                <div class="description">
                                                    <span class="product-title">Vintage Camera</span>
                                                    <span class="price number">$249.50</span>
                                                </div>
                                            </a>
                                        </li>
                                    </ul>
                                    <hr>
                                    <div class="cart-controls">
                                        <a class="btn btn-sm btn-filled" href="#">Checkout</a>
                                        <div class="list-inline pull-right">
                                            <span class="cart-total">Total: </span>
                                            <span class="number">$289.40</span>
                                        </div>
                                    </div>
                                </div>
                                <!--end of widget-->
                            </div>
                        </div>
                        <div class="module widget-handle language left">
                            <ul class="menu">
                                <li class="has-dropdown">
                                    <a href="#">ENG</a>
                                    <ul>
                                        <li>
                                            <a href="#">French</a>
                                        </li>
                                        <li>
                                            <a href="#">Deutsch</a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!--end of module group-->
                </div>
            </nav>
        </div>
            {% block content %}
            {% endblock %}
            <footer class="footer-1 bg-dark">
                <div class="container">
                    <div class="row">
                        <div class="col-md-3 col-sm-6">
                            <div class="widget">
                                <ul class="link-list recent-posts">
                                 {% for category in categories %}
                                    <li>
                                        <a href="{% url 'clothes:creat_good_list' category=category.id user_site=user_site %}">{{category.title}}</a>
                                    </li>
                                 {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    <!--end of row-->
                    <div class="row">
                        <div class="col-sm-6">
                            <span class="sub">&copy; Copyright 2015 - Medium Rare</span>
                        </div>
                    </div>
                </div>
                <!--end of container-->
                <a class="btn btn-sm fade-half back-to-top inner-link" href="#top">Top</a>
            </footer>
        </div>
        <script src="{% static 'clothes/js/jquery.min.js' %}"></script>
        <script src="{% static 'clothes/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'clothes/js/flickr.js' %}"></script>
        <script src="{% static 'clothes/js/flexslider.min.js' %}"></script>
        <script src="{% static 'clothes/js/lightbox.min.js' %}"></script>
        <script src="{% static 'clothes/js/masonry.min.js' %}"></script>
        <script src="{% static 'clothes/js/twitterfetcher.min.js' %}"></script>
        <script src="{% static 'clothes/js/spectragram.min.js' %}"></script>
        <script src="{% static 'clothes/js/ytplayer.min.js' %}"></script>
        <script src="{% static 'clothes/js/countdown.min.js' %}"></script>
        <script src="{% static 'clothes/js/smooth-scroll.min.js' %}"></script>
        <script src="{% static 'clothes/js/parallax.js' %}"></script>
        <script src="{% static 'clothes/js/scripts.js' %}"></script>
        <script src="{% static 'js/js.cookie.min.js' %}"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

        <script type="text/javascript">
            var csrftoken = Cookies.get('csrftoken');
            function csrfSafeMethod(method) {
                // these HTTP methods do not require CSRF protection
                return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }
            $.ajaxSetup({
                beforeSend: function(xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });
            $(document).ready(function(){
                $(document).on("blur", ".update-category", function() {
                    var id = $(this).data('id')
                    var text = $(this).text()
                    $.ajax({
                      url: "{% url 'clothes:update_category' user_site=user_site %}",
                      type: 'GET',
                      data:{id:id, text:text},
                      error: function(jqXHR, textStatus, errorThrown) {
                          alert(jqXHR.responseText)
                      },
                      success:function (data) {
                        alert(data)
                      }
                    })
                  });
                $(document).on("click", ".delete-category", function(){
                    var id = $(this).data('id')
                    var _this = $(this)
                    $.ajax({
                        url: "{% url 'clothes:delete_category' user_site=user_site %}",
                        type: 'GET',
                        data: {id:id},
                        error: function(jqXHR, textStatus, errorThrown) {
                          alert(jqXHR.responseText) },
                        success: function(data) {
                            _this.closest('li').remove()
                        },
                    })
                });
                $(document).on("click", ".pen-update", function(){
                    var id = $(this).data('id')
                    $('.update-data[data-id="'+id+'"]').attr('contenteditable', true).focus();
                });
                $(document).on("blur", ".update-data", function(){
                    $(this).attr('contenteditable', false)
                })
                {% block domready %}
                {% endblock %}
            });  
        </script>

    </body>
    {% block modal %}
    {% endblock %}
</html>

constructor_site/templates/clothes/constructor-site/information.html
{% extends 'clothes/constructor-site/base.html' %}
{% load static %}
{% load sale_tags %}
{% block content %}
<section class="page-title page-title-2 image-bg overlay parallax">

                <div class="background-image-holder">
                  {% get_additional_data 'phototoslide' user_site as phototoslide %}
                  <img alt="Background Image" class="background-image update-photo" src="{{phototoslide.photo.url}}" data-element_id="{{phototoslide}}">
                </div>


                <div class="container">
                    <div class="row">
                        <div class="col-md-6">

                           {% get_additional_data 'textonslid' user_site as textonslid %}
                              <h2 class="uppercase mb8 update-additional-data" data-element_id="textonslid" data-type='label' contenteditable="true">
                                 {{textonslid|default:"Men's Shop"}}
                              </h2>

                           {% get_additional_data 'textonslid2' user_site as textonslid2 %}
                              <p class="lead mb0 update-additional-data" data-element_id="textonslid2" data-type='label' contenteditable="true">
                                 {{textonslid2|default:"Біздің өнімдер тек турциядан келеді"}}
                              </p>
                        </div>
                    </div>
                    <!--end of row-->
                </div>
                <!--end of container-->
            </section>
            <input type="file" class="update-photo-on-slide" name="" value="upload photo">

<section>
                <div class="container">
                    <div class="row">
                        <div style="text-align: center; font-size: 20px" class="">
                           {% get_additional_data user_site 'textunderslide' as textunderslide %}
                              <p id="textunderslide">
                                 {{textunderslide.label|upper}}
                              </p>
                        </div>
                        <div class="col-md-10 text-right">
                            <span class="input-lh"></span>
                        </div>
                    </div>
                    <!--end of row-->
                    <div class="row">
                        <div class="col-sm-12">
                            <hr>
                        </div>
                    </div>
                    <!--end of row-->
                    <div class="col-md-4 col-sm-4 masonry-item col-xs-12">
                    <a href="{% url 'clothes:creat_good' user_site=user_site %}">
                      <div style="border: 4px dashed black; width: 200px; height: 200px;text-align: center; padding-top: 90px; ">
                         <span style="color:orange">Добавить товар</span>
                      </div> 
                    </a>
                    </div>
                    <div class="row masonry" id="good-content">
                    
                    
                      {% for good in goods %}
                         <div class="col-md-4 col-sm-4 masonry-item col-xs-12">
                          <span style="color:red" class="delete-good" data-id="{{good.id}}"><i class="fas fa-times"></i></span>
                            <div class="image-tile outer-title text-center">
                                <a href="{% url 'clothes:detail' good=good.id user_site=user_site %}">
                                    <img alt="Pic" class="product-thumb" src="{{good.photo.url}}">
                                </a>

                                <form action="" method="post" enctype="multipart/form-data">
                                  <div class="example-1">
                                    <div class="form-group">
                                      <label class="label">
                                        <i class="material-icons">attach_file</i>
                                        <span class="title">Добавить файл</span>
                                        <input type="file" class="change-photo" data-id="{{good.id}}">
                                      </label>
                                    </div>
                                  </div>
                                </form>


                                <div class="title">
                                    <h5 class="mb0 update-good" contenteditable="true" data-id="{{good.id}}" data-type='title'>{{good.title}}</h5>
                                    <span class="display-block mb16">$<span class="update-good" contenteditable="true" data-id="{{good.id}}" data-type='price'>{{good.price}}</span></span>
                                </div>
                            </div>
                        </div>
                      {% endfor %}
                    </div>
                     
                    <!--end of row-->
                </div>
                <!--end of container-->
            </section>
            <section>
                <div class="container">
                    <div class="row">
                        <div class="col-sm-10 col-sm-offset-1">
                            <!--end of post snippet-->
                            <div class="comments">
                                <h5 class="uppercase">
                                 {% get_additional_data 'comments' user_site as comments %}
                                    <p  id="comments">
                                       {{comments.label|default:"--"}}
                                    </p>
                                </h5>
                                <ul class="comments-list">
                                    <li>
                                        <div class="avatar">
                                            {% get_additional_data 'photouser1' user_site as photouser1 %}
                                                   <p  id="photouser1">
                                                      <img src="{{photouser1.photo.url|default:'--'}}">
                                                   </p>
                                        </div>
                                        <div class="comment">
                                            <span class="uppercase author">
                                               {% get_additional_data 'Usercomment1' user_site as Usercomment1 %}
                                                <p  id="Usercomment1">
                                                   {{Usercomment1.label|default:"--"}}
                                                </p>
                                            </span>
                                            <p>
                                                {% get_additional_data 'comment1' user_site as comment1 %}
                                                   <p  id="comment1">
                                                      {{comment1.label|default:"--"}}
                                                   </p>
                                            </p>
                                        </div>
                                        <ul>
                                            <li>
                                                <div class="avatar">
                                                   {% get_additional_data 'photouser2' user_site as photouser2 %}
                                                      <p  id="photouser2">
                                                         <img src="{{photouser2.photo.url|default:'--'}}">
                                                      </p>
                                                </div>
                                                <div class="comment">
                                                    <span class="uppercase author">
                                                       {% get_additional_data 'Usercomment2' user_site as Usercomment2 %}
                                                         <p  id="Usercomment2">
                                                            {{Usercomment2.label|default:"--"}}
                                                         </p>
                                                    </span>
                                                    <p>
                                                        {% get_additional_data 'comment2' user_site as comment2 %}
                                                            <p  id="comment2">
                                                               {{comment2.label|default:"--"}}
                                                            </p>
                                                    </p>
                                                </div>
                                            </li>
                                        </ul>
                                    </li>
                                    <li>
                                        <div class="avatar">
                                            {% get_additional_data 'photouser3' user_site as photouser3 %}
                                                <p  id="photouser3">
                                                   <img src="{{photouser3.photo.url|default:'--'}}">
                                                </p>
                                        </div>
                                        <div class="comment">
                                            <span class="uppercase author">
                                               {% get_additional_data 'Usercomment3' user_site as Usercomment3 %}
                                                   <p  id="Usercomment3">
                                                      {{Usercomment3.label|default:"--"}}
                                                   </p>
                                            </span>
                                            <p>
                                                {% get_additional_data 'comment2' user_site as comment2 %}
                                                   <p  id="comment2">
                                                      {{comment2.label|default:"--"}}
                                                   </p>
                                            </p>
                                        </div>
                                    </li>
                                </ul>
                                <hr>
                                {% get_additional_data 'textundercomment' user_site as textundercomment %}
                                    <h5 class="uppercase"  id="textundercomment">
                                       {{textundercomment.label|default:"--"}}
                                    </h5>
                                <form>
                                    <input name="name" type="text" placeholder="Your Name" />
                                    <input name="email" type="text" placeholder="Email Address" />
                                    <textarea rows="3" placeholder="Comment"></textarea>
                                    <input type="submit" value="Leave Comment" />
                                </form>
                            </div>
                            <!--end of comments-->
                        </div>
                        <!--end of nine col-->
                    </div>
                    <!--end of container row-->
                </div>
                <!--end of container-->
            </section>

{% endblock %}

{% block domready %}
  $(document).on("change", ".change-photo", function() {
    var id = $(this).data('id')
    alert(id)
  })


  $(document).on("blur", ".update-good", function() {
    var id = $(this).data('id')
    var type = $(this).data('type')
    var text = $(this).text()
    $.ajax({
      url: "{% url 'clothes:update_title' user_site=user_site %}",
      type: 'GET',
      data:{id:id, text:text, type: type},
      error: function(jqXHR, textStatus, errorThrown) {
          alert(jqXHR.responseText)
      },
      success:function (data) {
      }
    })
  });
  $(document).on("blur", ".update-additional-data", function() {
    var element_id = $(this).data('element_id')
    var type = $(this).data('type')
    var text = $(this).text()
    $.ajax({
      url: "{% url 'clothes:update_additional_data' user_site=user_site %}",
      type: 'GET',
      data:{element_id:element_id, text:text, type: type},
      error: function(jqXHR, textStatus, errorThrown) {
          alert(jqXHR.responseText)
      },
      success:function (data) {
      }
    })
  });
  

  $(document).on("click", ".delete-good", function() {
    var id = $(this).data('id')
    var _this = $(this)
    $.ajax({
      url: "{% url 'clothes:delete_good' user_site=user_site %}",
      type: 'GET',
      data:{id:id},
      error: function(jqXHR, textStatus, errorThrown) {
          alert(jqXHR.responseText)
      },
      success:function (data) {
      _this.closest('.col-md-4').remove()
      }
    })
  });

  $(document).on("click", ".update-photo-on-slide", function() {
    var element_id = $('.update-photo').data('element_id')
    alert(element_id)
  });

  
{% endblock %}