constructor_site/constructor_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',auth_views.LoginView.as_view(),name='login'),
    path('', include('management_site.urls', namespace='management_site')),
    path('figma/', include('figma.urls')),
    path('<str:user_site>/sale/clothes/', include('sale_clothes.urls')),
    path('crm/', include('mini_crm.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, 
		                 document_root=settings.MEDIA_ROOT)

constructor_site/figma/urls.py
from django.urls import path
from . import views

app_name = 'figma'
urlpatterns = [
    path('',views.ClientIndexView.as_view(), name ='index'),

    
] 

constructor_site/management_site/urls.py
from django.urls import path
from . import views
app_name = 'management'

urlpatterns = [
    path('', views.InformationView.as_view(), name='information_page'),
    path('mysite', views.MySiteListView.as_view(), name='mysite_page'),
    path('site/list', views.SiteListView.as_view(), name='site_list_page'),
    path('site/list/<int:category>', views.SiteListView.as_view(), name='site_list_page'),
    path('user/site/create/<int:site>', views.UserSiteCreateView.as_view(), name='user_site_page'),
    path('user/registration', views.UserRegistrationView.as_view(), name='user_registration_page'),
]

constructor_site/templates/management/base.html
<!DOCTYPE html>
<html>
<head>
	{% load static %}
	 <title>Bootstrap Example</title>
	  <meta charset="utf-8">
	  <meta name="viewport" content="width=device-width, initial-scale=1">
	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
	  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
	{% block content %}
    {% endblock %}
</body>
</html>

constructor_site/templates/management/information.html
{% extends 'management/base.html' %}
{% block content %}
	<a href="{% url 'login' %}">Войти</a>
	<a href="{% url 'management:user_registration_page' %}">Регистрация</a>
	{% if messages %}
	    {% for message in messages %}
		    <div class="alert alert-{{ message.tags }}">
		    	<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
			    {{ message }}
			</div>
	    {% endfor %}
	{% endif %}
	<form action="{% url 'management:information_page'%}" method="post">
		{% csrf_token %}
		<p>Введите ваше имя</p>
		{{demand_form.title}}
		<p>Введите номер телефона</p>
		{{demand_form.phone}}
		<br><br>
		<p>Чтобы сохранить ножми эту Кнопку</p>
		<input style="color:red;width: 100px;" type="submit" value="save">
	</form>
{% endblock %}

constructor_site/templates/management/mysite.html
{% extends 'management/base.html' %}
{% block content %}
<a href="{% url 'management:site_list_page' %}">Добавить сайт</a>
{% for mysite in mysites %}
    {{mysite.site.title}}
{% empty %}
	У вас нет выбранного сайта
{% endfor %}
{% endblock %}

constructor_site/templates/management/site_list.html
{% extends 'management/base.html' %}
{% block content %}

	{% for site in sites %}
	<div>
		<p style="color:green" >{{site.title}} <span style="color:red" >${{site.cost}}</span></p>
		<img style="width: 200px; height: auto" src="{{site.photo.url}}">
        <p><a href="{% url 'management:user_site_page' site=site.id %}">Выбрать сайт</a></p>
        <p><a href="{% url site.client_url user_site='wefw' %}">Предасмотр сайт</a></p>
	</div>
	{% endfor %}

	{% for category in categories %}
		<a href="{% url 'management:site_list_page' category=category.id %}">{{category.title}}</a>
	{% endfor %}

{% endblock %}