constructor_site/constructor_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',auth_views.LoginView.as_view(),name='login'),
    path('', include('management_site.urls', namespace='management_site')),
    path('figma/', include('figma.urls')),
    path('<str:user_site>/sale/clothes/', include('sale_clothes.urls')),
    path('crm/', include('mini_crm.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, 
		                 document_root=settings.MEDIA_ROOT)

constructor_site/figma/urls.py
from django.urls import path
from . import views

app_name = 'figma'
urlpatterns = [
    path('',views.ClientIndexView.as_view(), name ='index'),

    
] 

constructor_site/sale_clothes/urls.py
from django.urls import path
from . import views

app_name = 'clothes'
urlpatterns = [
    path('',views.ClientIndexView.as_view(), name ='index'),
    path('good/list/<int:category>/',views.GoodListView.as_view(), name ='good_list'),
    path('good/list/<int:category>/<int:subcategory>',views.GoodListView.as_view(), name ='good_list'),
    path('detail/<int:good>',views.DetailView.as_view(), name ='detail'),
    path('add/bag/<int:good>',views.AddBagView.as_view(), name ='add_bag'),
    path('creat/index',views.ConstructIndexView.as_view(), name ='creat_index'),
    path('creat/good/list/<int:category>',views.CreatGoodListView.as_view(), name ='creat_good_list'),
    path('creat/category',views.CategoryCreateView.as_view(), name ='creat_category'),
    path('creat/good',views.GoodCreateView.as_view(), name ='creat_good'),
    path('creat/subcategory/<int:category>',views.SubcategoryCreateView.as_view(), name ='creat_subcategory'),
    path('update/title/good',views.UpdateTitleGoodView.as_view(), name ='update_title'),
    path('update/additional/data',views.UpdateOrCreateAdditionalDataView.as_view(), name ='update_additional_data'),
    path('update/category',views.UpdateCategoryView.as_view(), name ='update_category'),
    path('delete/category',views.DeleteCategoryView.as_view(), name ='delete_category'),
    path('delete/good',views.DeleteGoodView.as_view(), name ='delete_good'),

] 

constructor_site/figma/models.py
from django.db import models


# список категории
class Category(models.Model):
    title = models.CharField(max_length=30) 

    def __str__(self):
    	return self.title


# список товаров
class Good(models.Model):
    title = models.CharField(max_length=30)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    top = models.BooleanField(default=False)
    category = models.ForeignKey(Category,on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.title			
    			

constructor_site/figma/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateResponseMixin, View
from .models import Good, Category


class ClientIndexView(TemplateResponseMixin,View):
    template_name = 'figma/client-site/index.html'

    def get (self, request, category=None):
        categories = Category.objects.all()
        goods = Good.objects.filter(top=True)
        if category:
        	goods = goods.filter(category=category)
        return self.render_to_response({
        	'categories': categories, 'goods': goods})




  

constructor_site/templates/figma/constructor-site/base.html
<!DOCTYPE html>
<html>
<head>
  {% load static %}

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
	
  <link rel="stylesheet" href="{% static 'css/figma/bootstrap.min.css' %}"/>
  <link rel="stylesheet" href="{% static 'css/figma/font-awesome.min.css' %}"/>
  <link rel="stylesheet" href="{% static 'css/figma/flaticon.css' %}"/>
  <link rel="stylesheet" href="{% static 'css/figma/slicknav.min.css' %}"/>
  <link rel="stylesheet" href="{% static 'css/figma/jquery-ui.min.css' %}"/>
  <link rel="stylesheet" href="{% static 'css/figma/owl.carousel.min.css' %}"/>
  <link rel="stylesheet" href="{% static 'css/figma/animate.css' %}"/>
  <link rel="stylesheet" href="{% static 'css/figma/app.css' %}"/>
  <link rel="stylesheet" href="{% static 'css/figma/fonts.css' %}"/>
  <link rel="stylesheet" href="{% static 'css/figma/style.css' %}"/>
	<title></title>
</head>
<body>
  <header class="header-section">
    <div class="header-top">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center text-lg-left">
            <!-- logo -->
        
              <img src="{% static 'figma/img/logo.png' %}" alt="">       
                 </div>
          <!--<div class="col-xl-6 col-lg-5">
            <form class="header-search-form">
              <input type="text" placeholder="Поиск товара ....">
              <button><i class="flaticon-search"></i></button>
            </form>
          </div>-->
        </div>
      </div>
    </div>
    <nav class="main-navbar">
      <div class="container">
        <!-- menu -->
        <ul class="main-menu">
          <li><a href="#">Главная страница</a></li>
          <li><a href="#">Для парня / отца</a></li>
          <li><a href="#">Для девушки / мамы</a></li>
          <li><a href="#">Для новорожденного</a></li>


          <!--li><a href="#">Shoes</a>
            <ul class="sub-menu">
              <li><a href="#">Sneakers</a></li>
              <li><a href="#">Sandals</a></li>
              <li><a href="#">Formal Shoes</a></li>
              <li><a href="#">Boots</a></li>
              <li><a href="#">Flip Flops</a></li>
            </ul>
          </li-->
          <!--li><a href="#">Pages</a>
            <ul class="sub-menu">
              <li><a href="./product.html">Product Page</a></li>
              <li><a href="./category.html">Category Page</a></li>
              <li><a href="./categorynew.html">Cart Page</a></li>
              <li><a href="./checkout.html">Checkout Page</a></li>
              <li><a href="./contact.html">Contact Page</a></li>
            </ul>
          </li>
          <li><a href="#">Blog</a></li-->
        </ul>
      </div>
    </nav>
  </header>
	{% block content %}

	{% endblock %}

  <script src="{% static 'js/figma/app.js' %}"></script>

  <script src="{% static 'js/figma/hoverable-collapse.js' %}"></script> 
  <script src="{% static 'js/figma/jquery-3.2.1.min.js' %}"></script>
  <script src="{% static 'js/figma/jquery-ui.min.js' %}"></script>
  <script src="{% static 'js/figma/jquery.nicescroll.min.js' %}"></script>
  <script src="{% static 'js/figma/jquery.slicknav.min.js' %}"></script>
  <script src="{% static 'js/figma/jquery.zoom.min.js' %}"></script>
  <script src="{% static 'js/figma/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/figma/main.js' %}"></script>
  <script src="{% static 'js/figma/map.js' %}"></script>
  <script src="{% static 'js/figma/off-canvas.js' %}"></script>
  <script src="{% static 'js/figma/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/figma/Preview.js' %}"></script>
  <script src="{% static 'js/figma/template.js' %}"></script>
  <script src="{% static 'js/js.cookie.min.js' %}"></script>
	
	<script type="text/Javascript">
    	var csrftoken = Cookies.get('csrftoken');
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });
        $(document).ready(function(){
            {% block domready %}
            {% endblock %}
        });

    </script>
{%block modal%} {%endblock%}
<br><br>
<section class="footer-section">
    <div class="social-links-warp">
      <div class="container">
        <div class="social-links">
          <a href="" class="instagram"><i class="fa fa-instagram"></i><span>instagram</span></a>
          <a href="" class="google-plus"><i class="fa fa-google-plus"></i><span>g+plus</span></a>
          <a href="" class="pinterest"><i class="fa fa-pinterest"></i><span>pinterest</span></a>
          <a href="" class="facebook"><i class="fa fa-facebook"></i><span>facebook</span></a>
          <a href="" class="twitter"><i class="fa fa-twitter"></i><span>twitter</span></a>
          <a href="" class="youtube"><i class="fa fa-youtube"></i><span>youtube</span></a>
          <a href="" class="tumblr"><i class="fa fa-tumblr-square"></i><span>tumblr</span></a>
        </div>
      </div>
    </div>
  </section>

</body>
</html>

constructor_site/templates/figma/constructor-site/index.html
{% extends 'figma/constructor-site/base.html' %}
{% block content %}
  <section class="category-section spad">
    <div class="container">
      <div class="row">
      
        <div class="col-lg-3 order-1 order-lg-1">
          <div class="filter-widget">
            <h2 class="fw-title">Категории</h2>
             <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myCategory">Добавить категории   </button>
             <a href="{% url 'figma:creategood' user_site=user_site %}">
             Добавить товар</a>
             <ul class="category-menu">
                {% for category in categories %}
                <li >
                   <a href="{% url 'figma:constructor' category.id %}">{{category.title}}
                     <span class="delete-category" data-id ="{{category.id}}">
                       X
                     </span>
                      <span class="update-category btn btn-primary" data-id ="{{category.id}} " data-toggle="modal" data-target="#updateCategory">
                       ®
                      </span>
                    </a>

                </li>
                 {% endfor %}
                </ul>
              </div>
            </div>

        <div class="col-lg-9  order-2 order-lg-2 mb-5 mb-lg-0">
            
          <div class="row">
            <div class="col-lg-12">
              <div class="text-center">
                <h2 class="border-b">Топ продаж</h2>
              </div>
            </div>
            
{%for good in goods %}

            <div class="col-lg-4 col-sm-6">

              <div class="product-item">
                <br>
                <div class="pi-pic">
                <br>
                       
                    </div>
                </div>

                <div class="pi-text">
                 <div>

    <a href="{% url 'figma:constructor' user_site=user_site %}"></a>


    {% if good.photo %}
    <img src="{{good.photo.url}}" style="width: 300px; height: 200px;">
    {% endif %}

<a href=""><span class="update-good btn btn-primary" data-id ="{{good.id}} " data-toggle="modal" data-target="#updateGood">редактировать</span></a>
 <a href="">
   <span class="remove-good" data-id = "{{good.id}}">
      X
   </span>
</a>
<br>

{{good.price}} тг
{{good.title}}

                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </section>










{% endblock %}
{% block modal %}
<div class="modal" id="myCategory">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Modal Heading</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
        <form action="{% url 'figma:createcategory' user_site=user_site %}" method="post">
          {% csrf_token %}
      <p>Введите название категории</p>
      {{category_form.title}}
          <input type="submit"  value="save">
        </form>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>

    </div>
  </div>
</div>


<div class="modal" id="myGood">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Modal Heading</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
        <form action="{% url 'figma:creategood' user_site %}" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <p>Введите название товара</p>
          {{good_form.as_p}}
          <input type="submit" value="save">
        </form>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>

    </div>
  </div>
</div>


<div class="modal" id="updateGood">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Modal Heading</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body" id="good-content">

      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>

    </div>
  </div>
</div>


<div class="modal" id="updateCategory">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Modal Heading</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body" id="category-content">

      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>

    </div>
  </div>
</div>


{% endblock %}
{% block domready %}
  $(document).on("click", ".delete-category", function() {

    event.preventDefault()
    var id = $(this).data('id')
    var _this = $(this)
    $.ajax({
            url: "{% url 'figma:category_delete' user_site=user_site %}",
            type: 'POST',
            data:{category_id: id},
          
            success:function (data) {

                _this.closest('li').remove()

            }

        })
  });

    
 $(document).on("click", ".remove-good", function() {
    event.preventDefault()
    var id = $(this).data('id')
    var _this = $(this)
    $.ajax({
            url: "{% url 'figma:good_delete' user_site=user_site %}",
            type: 'GET',
            data:{good_id: id},
            error: function(jqXHR, textStatus, errorThrown) {
                alert(jqXHR.responseText)
            },
            success:function (data) {
                _this.closest('div').remove()
            }
        })
  });
    

$(document).on("click", ".update-good", function() {
    event.preventDefault()
    var id = $(this).data('id')
    var _this = $(this)
    
    $.ajax({
            url: "{% url 'figma:update_good' user_site=user_site good=0 %}".replace('0', id),
            type: 'GET',
            data:{},
            error: function(jqXHR, textStatus, errorThrown) {
                alert(jqXHR.responseText)
            },
            success:function (data) {
            $('#good-content').html(data)   
              
                
            }
        })
    
  });


  $(document).on("click", ".update-category", function() {
    event.preventDefault()
    var id = $(this).data('id')
    var _this = $(this)
    
    $.ajax({
            url: "{% url 'figma:update_category' user_site=user_site category=0 %}".replace('0', id),
            type: 'GET',
            data:{},
            error: function(jqXHR, textStatus, errorThrown) {
                alert(jqXHR.responseText)
            },
            success:function (data) {
            $('#category-content').html(data)   
              
                
            }
        })
    
  });
{% endblock %}

constructor_site/templates/figma/constructor-site/update.html
<form action="{% url 'figma:update_good' good=good.id user_site=user_site %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
    <p>Введите name</p>
    {{good_form.title}}
    {{good_form.price}}
    {{good_form.top}}
    {{good_form.category}}
    {{good_form.photo}}

    <input type="submit" value="сохранить" style="color:blue;" >
</form>